<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Chrome Browser"
           tests="3"
           failures="1"
           errors="0"
           skipped="1"
           time="60.690">
  <properties />
            <testcase name="afterTest" time="0.000" classname="rawItemActivityBundle.US290_RawItemActivity">
                <failure type="java.io.FileNotFoundException"
                  message="Report_Excel\Report.xls (The process cannot access the file because it is being used by another process)"
              >
<![CDATA[java.io.FileNotFoundException: Report_Excel\Report.xls (The process cannot access the file because it is being used by another process)
  java.io.FileOutputStream.open(Native Method)
  java.io.FileOutputStream.<init>(Unknown Source)
  java.io.FileOutputStream.<init>(Unknown Source)
  jxl.Workbook.createWorkbook(Workbook.java:338)
  jxl.Workbook.createWorkbook(Workbook.java:320)
  common.Reporter.updateTotalCount(Reporter.java:192)
  sprint2.AbstractTest.afterTest(AbstractTest.java:154)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
  org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
  org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
  org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
  org.testng.TestRunner.afterRun(TestRunner.java:1014)
  org.testng.TestRunner.run(TestRunner.java:621)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
  org.testng.SuiteRunner.run(SuiteRunner.java:240)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
  org.testng.TestNG.run(TestNG.java:1057)
  org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
  org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
  org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
      </failure>

          </testcase>
  
            <testcase name="afterSuite" time="0.0" classname="rawItemActivityBundle.US290_RawItemActivity">
          <skipped />
    </testcase>
  
            <testcase name="rawItemActivityBundle_US290_TC2235" time="60.690" classname="rawItemActivityBundle.US290_RawItemActivity" />
      
</testsuite>
